### ISSUE TITLE
problem with WOR mode

### ISSUE THREAD

**Issue by AlekseyLevchenkoTMN** [pkarsy/CC1101_RF#1]
Hello my friend. I'm using your CC1101_RF library and WOR example, which I've redesigned for arduino (I'm using pro mini 3.3v 8mhz). I came across the fact that in wor mode, the receiver wakes up due to third-party signals (for example, signals from a different address, with a different sync word or frequency), and without interruption on GDO0 (therefore, this event cannot be worked on the microcontroller, because it wakes up on an interrupt). At the same time, the consumption of cc1101 increases to 18 mA (and lasts constantly), which is unacceptable for an autonomous project. I have an assumption that the wor function of your library lacks some kind of register responsible for putting the radio module back into sleep mode when an incorrect packet is received (mismatch of address or frequency). Please tell me what my problem is.

And there is also no setAddress(addr) function in the library (but in the description it is).  

Best regards, 
Alex

**Comment by pkarsy** [comment]
Yes both reports seem to be bugs
Give me some time to figure it out

**Comment by heikoxxxx** [comment]
Hi, 
thanks for that great library. Working also on an project with 
arduino pro mini and CC1101, which need a low power consumtion. 
Library is working well and i get an total consumtion of 0,3µa at all.
Problem is the waking up of CC1101 by WOR and the GDO0 is never been triggered. So the MCU is not waked up and i cannot set back to WOR mode. 

Have spend now several hours to find any fix and tested some changes, but no result.
Perhaps is you have any idea, you can tell me and i will do testings for you. 

Thanks Heiko

**Comment by pkarsy** [comment]
I have been working on the bug yesterday I have very little free time
unfortunately. I know where the problem is, And I will try to find a
solution the next days
Thank you
Panagiotis

Στις Σάβ 20 Ιαν 2024 στις 5:55 μ.μ., ο/η heikoxxxx ***@***.***>
έγραψε:

**Comment by pkarsy** [comment]
> Hi, thanks for that great library. Working also on an project with arduino pro mini and CC1101, which need a low power consumtion. Library is working well and i get an total consumtion of 0,3µa at all. Problem is the waking up of CC1101 by WOR and the GDO0 is never been triggered. So the MCU is not waked up and i cannot set back to WOR mode.
> 
> Have spend now several hours to find any fix and tested some changes, but no result. Perhaps is you have any idea, you can tell me and i will do testings for you.
> 
> Thanks Heiko

The  0,3µa if it is correct cannot be achieved by CC1101 in wor mode. Even the voltage regulator of the ProMini needs more quiescent current. Maybe is 0.3mA ? Anyway I have updated the library, fixing the bug reported by   AlekseyLevchenkoTMN and you can try the pingLowPower exmple. I dind not try it, but it could work fine with a proMini, although with higher current consumption due to the buildin leds

**Comment by pkarsy** [comment]
> Hello my friend. I'm using your CC1101_RF library and WOR example, which I've redesigned for arduino (I'm using pro mini 3.3v 8mhz). I came across the fact that in wor mode, the receiver wakes up due to third-party signals (for example, signals from a different address, with a different sync word or frequency), and without interruption on GDO0 (therefore, this event cannot be worked on the microcontroller, because it wakes up on an interrupt). At the same time, the consumption of cc1101 increases to 18 mA (and lasts constantly), which is unacceptable for an autonomous project. I have an assumption that the wor function of your library lacks some kind of register responsible for putting the radio module back into sleep mode when an incorrect packet is received (mismatch of address or frequency). Please tell me what my problem is.
> 
> And there is also no setAddress(addr) function in the library (but in the description it is).
> 
> Best regards, Alex

Hi
The new version of the library fixes the bug of GDO0 so WoR mode now works very reliably. The downside is that the GDO0 behavior is different. The pingLowPower example explains the new behavior
Thanks
Panagiotis

**Comment by pkarsy** [comment]
> And there is also no setAddress(addr) function in the library (but in the description it is).

There is no such function. There is however the
enableAddressCheck('#') (or any other byte 0x01 0x05 '1' 'A' etc)
 The use of enableAddressCheck() tells to the CC1101 chip to accept only packets having '#' as first byte. 
The construction of a packet having this byte '#' at the start is the responsibility of the developer. One easy way, is the use of printf(fmt,...) with the format having '#' as first character.

**Comment by heikoxxxx** [comment]
Hello Panagiotis,
thanks for that fix. I am doing some testings now on on my promini board. Your changes and WOR mode seems to work now and interrupt is correctly on GDO0 Pin (changed in code from Pin 9 to Interruptpin 2). On my Multimeter i see the power consumtion of hole system of 0.8 µa on a 18650 battery which 4.2V.
Every second the power goes up to 50 - 200 µa but that is fine i think. (It is the receiving intervall)
In Datasheet of CC1101 i found the table in 4.1 which tells the power consumtion of 0.5 µa in sleep state which wor enabled.I found that ProMini 168PA is working on 0.1 µa in sleep mode, so i think with enabled interrupt the total consumtion of 0,8µa at all is a great value. 

Thanks for fixing.

**Comment by AlekseyLevchenkoTMN** [comment]
> > Hello my friend. I'm using your CC1101_RF library and WOR example, which I've redesigned for arduino (I'm using pro mini 3.3v 8mhz). I came across the fact that in wor mode, the receiver wakes up due to third-party signals (for example, signals from a different address, with a different sync word or frequency), and without interruption on GDO0 (therefore, this event cannot be worked on the microcontroller, because it wakes up on an interrupt). At the same time, the consumption of cc1101 increases to 18 mA (and lasts constantly), which is unacceptable for an autonomous project. I have an assumption that the wor function of your library lacks some kind of register responsible for putting the radio module back into sleep mode when an incorrect packet is received (mismatch of address or frequency). Please tell me what my problem is.
> > And there is also no setAddress(addr) function in the library (but in the description it is).
> > Best regards, Alex
> 
> Hi The new version of the library fixes the bug of GDO0 so WoR mode now works very reliably. The downside is that the GDO0 behavior is different. The pingLowPower example explains the new behavior Thanks Panagiotis

Hi again. As a heikoxxxx user, I also tested the library update on the arduino pro mini. Everything works fine. Thanks a lot for fixing it. 
I still have one question, I would be grateful if you could help me with this. I need to take care of the security of my device. But if desired, someone can endlessly transmit data packets to my radio module or endlessly send a preamble. At the same time, the radio module will consume much more energy and drain the battery (I have already tested this). Is it possible to solve this problem?

**Comment by pkarsy** [comment]
> Hi again. As a heikoxxxx user, I also tested the library update on the arduino pro mini. Everything works fine. Thanks a lot for fixing it. I still have one question, I would be grateful if you could help me with this. I need to take care of the security of my device. But if desired, someone can endlessly transmit data packets to my radio module or endlessly send a preamble. At the same time, the radio module will consume much more energy and drain the battery (I have already tested this). Is it possible to solve this problem?

This is a DoS attack and generally it is difficult to defend against them. Many protocols suffer from them (for example WiFi). To answer your question, I can imagine a quite sophisticated protocol where the module waits for data only on a specified time slot. The chip never extends the listening time(even if receives a preamble, there is a CC1101 register setting for this ) and the sender must send a (encrypted and every time different, otherwise will be stolen) message in this time slot to wake up the module. It is extremely complicated and changes are it will again be vulnerable to a more clever DoS attack.
Note that with radio signal, there is a DoS attack you cannot avoid ! The attacker sends non-stop strong radio signals, disabling telecomunications (Ok this does not drain the battery but it disables the module anyway). Given all that, my guess is that you have to live with this.

**Comment by AlekseyLevchenkoTMN** [comment]
> > Hi again. As a heikoxxxx user, I also tested the library update on the arduino pro mini. Everything works fine. Thanks a lot for fixing it. I still have one question, I would be grateful if you could help me with this. I need to take care of the security of my device. But if desired, someone can endlessly transmit data packets to my radio module or endlessly send a preamble. At the same time, the radio module will consume much more energy and drain the battery (I have already tested this). Is it possible to solve this problem?
> 
> This is a DoS attack and generally it is difficult to defend against them. Many protocols suffer from them (for example WiFi). To answer your question, I can imagine a quite sophisticated protocol where the module waits for data only on a specified time slot. The chip never extends the listening time(even if receives a preamble, there is a CC1101 register setting for this ) and the sender must send a (encrypted and every time different, otherwise will be stolen) message in this time slot to wake up the module. It is extremely complicated and changes are it will again be vulnerable to a more clever DoS attack. Note that with radio signal, there is a DoS attack you cannot avoid ! The attacker sends non-stop strong radio signals, disabling telecomunications (Ok this does not drain the battery but it disables the module anyway). Given all that, my guess is that you have to live with this.

I understand. I have one last idea in case someone keeps sending preamble. To make the battery drain more slowly in this case, you can increase the WoR cycle. But in the library the maximum cycle is 1890ms. Is it possible to increase it? For example, up to 5-10 seconds. It would be nice to reduce battery drain.

I have an idea about this. But it is only feasible in conjunction with waking up the microcontroller. That is, MK simply puts the module into WoR mode a certain number of times. I tested this, the results were of course a little better, but not perfect.

**Comment by pkarsy** [comment]
> I understand. I have one last idea in case someone keeps sending preamble. To make the battery drain more slowly in this case, you can increase the WoR cycle. But in the library the maximum cycle is 1890ms. Is it possible to increase it? For example, up to 5-10 seconds. It would be nice to reduce battery drain. I have an idea about this. But it is only feasible in conjunction with waking up the microcontroller. That is, MK simply puts the module into WoR mode a certain number of times. I tested this, the results were of course a little better, but not perfect.

Hi I don't believe that this kind of DoS attach is a real threat to the application. However the solution you propose seems OK. The Microcontroller wakes using the watchdog timer and then enables the RF module for a very short period.
Mostly as a game I will try to implement a worNoPreamble() function (I cant say when, however). I don't know if this will help you but I am pretty sure it will make the RF to draw more current as it needs to stay active a little more time to get a full packet.

**Comment by AlekseyLevchenkoTMN** [comment]
> > I understand. I have one last idea in case someone keeps sending preamble. To make the battery drain more slowly in this case, you can increase the WoR cycle. But in the library the maximum cycle is 1890ms. Is it possible to increase it? For example, up to 5-10 seconds. It would be nice to reduce battery drain. I have an idea about this. But it is only feasible in conjunction with waking up the microcontroller. That is, MK simply puts the module into WoR mode a certain number of times. I tested this, the results were of course a little better, but not perfect.
> 
> Hi I don't believe that this kind of DoS attach is a real threat to the application. However the solution you propose seems OK. The Microcontroller wakes using the watchdog timer and then enables the RF module for a very short period. Mostly as a game I will try to implement a worNoPreamble() function (I cant say when, however). I don't know if this will help you but I am pretty sure it will make the RF to draw more current as it needs to stay active a little more time to get a full packet.

OK, thanks for the feedback. All the best!
