### ISSUE TITLE
incompatibility with atmega2560

### ISSUE THREAD

**Issue by AlekseyLevchenkoTMN** [pkarsy/CC1101_RF#2]
Hi, I'm sorry to bother you again. The fact is that my final project runs on atmega2560 (MegaCore on 8mhz frequency and 3.3V power). From the example (sleep), only this line is not compiled: sleep_bod_disable(); Without it, I managed to load the code, but the radio module did not receive data. He only woke up once and then the consumption of the circuit hung at 1.8mA. I tried out the same code on the arduino mega. The data was also not accepted. You wrote that the library should most likely work on any atmega. Maybe you know what's the matter, considering that I use atmega2560

**Comment by pkarsy** [comment]
Hi
Generally speaking low power mode is microcontroller specific. Most probably sleep_bod_disable() is unavailable in atmega2560 . This means it cannot disable BrownOutDetector in sleep mode. But again I have not this microcontroller so I cannot be sure. The problem that the MCU does not wake up from sleep most likely has to do with the interrupt handler. Some interrupts cannot wake up the MCU you have to check this. I suggest to run the "ping" example (it does not use interrupts neither sleep mode) in atmega256 to see if the library works and only then move to more advanced usage.

**Comment by AlekseyLevchenkoTMN** [comment]
You were right, the microcontroller didn't wake up because of the wrong interrupt handler in my code. This was due precisely to the features of the atmega2560 interrupts. I figured it out thanks to the arduino forum (https://forum.arduino.cc/t/getting-crazy-with-mega2560-sleep-modes-and-interrupts/862773/8 ) - atmega2560 interrupts on pins D2 and D3 are triggered only in LOW (or FALLING) mode. But the CC1101 issues an interrupt with a HIGH (or RISING) signal. In HIGH mode, only pins D18 and D19 work on the atmega2560. I connected GDO0 to D18 and changed some lines of code (I wrote in the Arduino IDE):


```
#define GDO0 18
#include <LowPower.h>
```

```
volatile byte GDO0_STATUS = LOW;
void isr() {
  if (GDO0_STATUS == LOW) GDO0_STATUS = digitalRead(GDO0);
}
```

```
void deepSleep() {
    Serial.println(F("MCU in sleep. CC1101 in WoR.\r\nWaiting for GDO0 to be asserted from RF chip."));
    Serial.flush();   // not sure if Serial.end() is doing that
    Serial.end();     // Disable the Serial port to save power or interference with the programmer pins
    radio.wor(1890);  // TODO flush queues
    while (1) {
       attachInterrupt(5, isr, HIGH);
       LowPower.powerDown(SLEEP_FOREVER, ADC_OFF, BOD_OFF);
       detachInterrupt(5);
       if (GDO0_STATUS == HIGH) {  // The interrupt handler did the change
         GDO0_STATUS = LOW;        // we reset it to LOW to be ready for the next time
         break;
     }
   }
   Serial.begin(9600);
}
```

```
void setup() {
   .
   .
   .
   pinMode(GDO0, INPUT);
}
```

It also turned out that D18 corresponds to the argument 5 for the attachInterrupt() function.
So everything worked for me (the "ping" example also works great).

By the way, BOD atmega2560 can still be disabled in code using the LowPower library and function LowPower.powerDown(SLEEP_FOREVER, ADC_OF, BOD_OFF); 
At the same time, the consumption in sleep mode becomes 5-10 µA less.

**Comment by pkarsy** [comment]
I find PCINT(Pin Change Interrupt) more useful because it can wake up the MCU from sleep AND use any Pin
This is the reason I use PCINT for the "pingLowPower" example
